name: deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          name: "projects/greg-finley/locations/us-central1/functions/planetscale-ping"
          runtime: "python311"
          entry_point: "run"
          source_dir: "ping"
          memory_mb: 128
          secret_environment_variables: "MYSQL_CONFIG=projects/greg-finley/secrets/MYSQL_CONFIG/versions/latest"
          timeout: 30
          event_trigger_type: "providers/cloud.pubsub/eventTypes/topic.publish"
          event_trigger_resource: "projects/greg-finley/topics/planetscale-ping"
          event_trigger_service: "pubsub.googleapis.com"
          min_instances: 0
          max_instances: 1
